service: lambda-test-serverless

custom:
  region: "us-east-2"
  serviceName: 'test-rest'
  authorizer: "arn:aws:cognito-idp:us-east-2:606727731259:userpool/us-east-2_g5KQWNye0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-2
  environment:
    DYNAMODB_TABLE: lambdaRestServerlessProd

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: create.main
    events:
      - http:
          path: ${self:custom.serviceName}
          method: put
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}

  list:
    handler: list.main
    events:
      - http:
          path: ${self:custom.serviceName}
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}

  get:
    handler: get.main
    events:
      - http:
          path: ${self:custom.serviceName}/{id}
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}

  update:
    handler: update.main
    events:
      - http:
          path: ${self:custom.serviceName}/{id}
          method: post
          cors: true
          authorizer:
            arn: ${self:custom.authorizer}

